# NumberAdder Example

We are going to create a number adder example. This number adder has two variables, `x` and `y`, that are indexed with a `year` label.

In [1]:
import paramtools

class NumberAdder(paramtools.Parameters):
    defaults = {
        "schema": {
            "labels": {
                "year": {
                    "type": "int", "validators": {"range": {"min": 2000, "max": 2030}}
                },
            }
        },
        "x": {
            "title": "X",
            "description": "X-axis",
            "type": "float",
            "value": [{"year": 2000, "value": 2}],
            "validators": {
                "range": {
                    "min": 0, "max": "y"
                }
            }
        },
        "y": {
            "title": "Y",
            "description": "Y-axis",
            "type": "int",
            "value": [{"year": 2000, "value": 50}],
            "validators": {
                "range": {
                    "min": "x", "max": 100,
                }
            }
        }
    }
    
    def run(self):
        if self.array_first:
            return self.x * self.y
        else:
            return sum([
                x["value"] * y["value"] for x, y in zip(self.x, self.y)
            ])

In [2]:
adder = NumberAdder()

adder.run()

100.0

**Access `x` directly as an attribute on the `adder` instance:**

In [3]:
adder.x

[OrderedDict([('year', 2000), ('value', 2.0)])]

**Acccess `x` through the `sel` attribute:**

In [4]:
adder.sel["x"]

Values([
  {'year': 2000, 'value': 2.0},
])

**We can update `x` easily, too:**

In [5]:
adder.adjust({"x": 4})

OrderedDict([('x', [OrderedDict([('value', 4.0)])])])

In [6]:
adder.sel["x"]

Values([
  {'year': 2000, 'value': 4.0},
])

In [7]:
adder.adjust({"x": [{"year": 2010, "value": 8}]})

OrderedDict([('x', [OrderedDict([('year', 2010), ('value', 8.0)])])])

In [8]:
adder.sel["x"]

Values([
  {'year': 2000, 'value': 4.0},
  {'year': 2010, 'value': 8.0},
])

**Validate user inputs:**

In [9]:
adder.adjust({"x": "abc"})

ValidationError: {
    "errors": {
        "x": [
            "Not a valid number: abc."
        ]
    }
}

In [10]:
adder = NumberAdder()

adder.adjust({"y": [{"value": 1}]})

ValidationError: {
    "errors": {
        "y": [
            "y 1 < min 2.0 x[year=2000]"
        ]
    }
}

**Access values as numpy arrays and use ParamTools' powerful extend rules:**

In [20]:
adder = NumberAdder(array_first=True, label_to_extend="year")

In [21]:
adder.x

array([2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2.,
       2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2.])

In [22]:
adder.sel["x"]

Values([
  {'year': 2000, 'value': 2.0},
  {'year': 2001, 'value': 2.0, '_auto': True},
  {'year': 2002, 'value': 2.0, '_auto': True},
  {'year': 2003, 'value': 2.0, '_auto': True},
  {'year': 2004, 'value': 2.0, '_auto': True},
  {'year': 2005, 'value': 2.0, '_auto': True},
  {'year': 2006, 'value': 2.0, '_auto': True},
  {'year': 2007, 'value': 2.0, '_auto': True},
  {'year': 2008, 'value': 2.0, '_auto': True},
  {'year': 2009, 'value': 2.0, '_auto': True},
  {'year': 2010, 'value': 2.0, '_auto': True},
  {'year': 2011, 'value': 2.0, '_auto': True},
  {'year': 2012, 'value': 2.0, '_auto': True},
  {'year': 2013, 'value': 2.0, '_auto': True},
  {'year': 2014, 'value': 2.0, '_auto': True},
  {'year': 2015, 'value': 2.0, '_auto': True},
  {'year': 2016, 'value': 2.0, '_auto': True},
  {'year': 2017, 'value': 2.0, '_auto': True},
  {'year': 2018, 'value': 2.0, '_auto': True},
  {'year': 2019, 'value': 2.0, '_auto': True},
  {'year': 2020, 'value': 2.0, '_auto': True},
  {'year': 2021, 'v

**Updated values are automatically extended using intuitive rules**

In [23]:
adder.adjust({"x": [{"year": 2005, "value": 10}, {"year": 2010, "value": 25}]})

OrderedDict([('x',
              [OrderedDict([('year', 2005), ('value', 10.0)]),
               OrderedDict([('year', 2010), ('value', 25.0)])])])

In [24]:
adder.x

array([ 2.,  2.,  2.,  2.,  2., 10., 10., 10., 10., 10., 25., 25., 25.,
       25., 25., 25., 25., 25., 25., 25., 25., 25., 25., 25., 25., 25.,
       25., 25., 25., 25., 25.])

**Use the Query API to select values of `x` that are less than 10 and not `_auto`**

In [25]:
adder.sel["x"] <= 10

QueryResult([
  {'year': 2000, 'value': 2.0}
  {'year': 2001, 'value': 2.0, '_auto': True}
  {'year': 2002, 'value': 2.0, '_auto': True}
  {'year': 2003, 'value': 2.0, '_auto': True}
  {'year': 2004, 'value': 2.0, '_auto': True}
  {'year': 2005, 'value': 10.0}
  {'year': 2006, 'value': 10.0, '_auto': True}
  {'year': 2007, 'value': 10.0, '_auto': True}
  {'year': 2008, 'value': 10.0, '_auto': True}
  {'year': 2009, 'value': 10.0, '_auto': True}
])

In [26]:
adder.sel["x"].missing("_auto")

QueryResult([
  {'year': 2000, 'value': 2.0}
  {'year': 2005, 'value': 10.0}
  {'year': 2010, 'value': 25.0}
])

In [27]:
(adder.sel["x"] <= 10) & adder.sel["x"].missing("_auto")

QueryResult([
  {'year': 2000, 'value': 2.0}
  {'year': 2005, 'value': 10.0}
])

**Use the built-in indexing logic to grow parameter values**

We will discuss this in more depth in the Tax-Calculator case-study

In [28]:
NumberAdder.defaults["x"]["indexed"] = True
class SimpleIndexed(NumberAdder):
    uses_extend_func = True # Provides a method for getting the indexing rate.
    array_first = True      # Another way to specify array_first access.
    label_to_extend = "year"
    
    index_rates = {
        year: 0.02 for year in range(2000, 2030)
    }
        

In [29]:
adder = SimpleIndexed()

In [30]:
adder.x

array([2.  , 2.04, 2.08, 2.12, 2.16, 2.2 , 2.24, 2.28, 2.33, 2.38, 2.43,
       2.48, 2.53, 2.58, 2.63, 2.68, 2.73, 2.78, 2.84, 2.9 , 2.96, 3.02,
       3.08, 3.14, 3.2 , 3.26, 3.33, 3.4 , 3.47, 3.54, 3.61])

In [31]:
adder.y

array([50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50,
       50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50])

In [32]:
adder.run()

array([100. , 102. , 104. , 106. , 108. , 110. , 112. , 114. , 116.5,
       119. , 121.5, 124. , 126.5, 129. , 131.5, 134. , 136.5, 139. ,
       142. , 145. , 148. , 151. , 154. , 157. , 160. , 163. , 166.5,
       170. , 173.5, 177. , 180.5])